# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import transManager_pb2 as transManager__pb2


class dataTransferStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.getAvailableDatasets = channel.unary_unary(
        '/helmsley.dataTransfer/getAvailableDatasets',
        request_serializer=transManager__pb2.Request.SerializeToString,
        response_deserializer=transManager__pb2.datasetResponse.FromString,
        )
    self.getVolumeFromDataset = channel.unary_unary(
        '/helmsley.dataTransfer/getVolumeFromDataset',
        request_serializer=transManager__pb2.Request.SerializeToString,
        response_deserializer=transManager__pb2.volumeResponse.FromString,
        )
    self.Download = channel.unary_stream(
        '/helmsley.dataTransfer/Download',
        request_serializer=transManager__pb2.Request.SerializeToString,
        response_deserializer=transManager__pb2.dcmImage.FromString,
        )
    self.DownloadMasks = channel.unary_stream(
        '/helmsley.dataTransfer/DownloadMasks',
        request_serializer=transManager__pb2.Request.SerializeToString,
        response_deserializer=transManager__pb2.dcmImage.FromString,
        )


class dataTransferServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def getAvailableDatasets(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getVolumeFromDataset(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Download(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DownloadMasks(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_dataTransferServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'getAvailableDatasets': grpc.unary_unary_rpc_method_handler(
          servicer.getAvailableDatasets,
          request_deserializer=transManager__pb2.Request.FromString,
          response_serializer=transManager__pb2.datasetResponse.SerializeToString,
      ),
      'getVolumeFromDataset': grpc.unary_unary_rpc_method_handler(
          servicer.getVolumeFromDataset,
          request_deserializer=transManager__pb2.Request.FromString,
          response_serializer=transManager__pb2.volumeResponse.SerializeToString,
      ),
      'Download': grpc.unary_stream_rpc_method_handler(
          servicer.Download,
          request_deserializer=transManager__pb2.Request.FromString,
          response_serializer=transManager__pb2.dcmImage.SerializeToString,
      ),
      'DownloadMasks': grpc.unary_stream_rpc_method_handler(
          servicer.DownloadMasks,
          request_deserializer=transManager__pb2.Request.FromString,
          response_serializer=transManager__pb2.dcmImage.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'helmsley.dataTransfer', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
