# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='common.proto',
  package='helmsley',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0c\x63ommon.proto\x12\x08helmsley\"-\n\x07Request\x12\x11\n\tclient_id\x18\x01 \x01(\x05\x12\x0f\n\x07req_msg\x18\x02 \x01(\t\"2\n\x0e\x63ommonResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07res_msg\x18\x02 \x01(\t\"i\n\tscoreInfo\x12\x11\n\trgroup_id\x18\x01 \x01(\x05\x12\x0f\n\x07rank_id\x18\x02 \x01(\x05\x12\x12\n\nrank_score\x18\x03 \x01(\x02\x12\x11\n\traw_score\x18\x04 \x03(\x02\x12\x11\n\tvol_score\x18\x05 \x03(\x02\"\xba\x02\n\nvolumeInfo\x12\x13\n\x0b\x66older_name\x18\x01 \x01(\t\x12\x13\n\x0b\x66older_path\x18\x02 \x01(\t\x12\x0c\n\x04\x64ims\x18\x03 \x03(\x05\x12\x13\n\x0borientation\x18\x04 \x03(\x02\x12\x12\n\nresolution\x18\x05 \x03(\x02\x12\x18\n\x10volume_loc_range\x18\x06 \x01(\x02\x12\x11\n\twith_mask\x18\x07 \x01(\x08\x12\x34\n\x0b\x64\x61ta_source\x18\x08 \x01(\x0e\x32\x1f.helmsley.volumeInfo.DataSource\x12\x12\n\nsample_img\x18\t \x01(\x0c\x12#\n\x06scores\x18\n \x01(\x0b\x32\x13.helmsley.scoreInfo\"/\n\nDataSource\x12\t\n\x05LOCAL\x10\x00\x12\n\n\x06SERVER\x10\x01\x12\n\n\x06\x44\x45VICE\x10\x02\x62\x06proto3')
)



_VOLUMEINFO_DATASOURCE = _descriptor.EnumDescriptor(
  name='DataSource',
  full_name='helmsley.volumeInfo.DataSource',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='LOCAL', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SERVER', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DEVICE', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=500,
  serialized_end=547,
)
_sym_db.RegisterEnumDescriptor(_VOLUMEINFO_DATASOURCE)


_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='helmsley.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='client_id', full_name='helmsley.Request.client_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='req_msg', full_name='helmsley.Request.req_msg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=71,
)


_COMMONRESPONSE = _descriptor.Descriptor(
  name='commonResponse',
  full_name='helmsley.commonResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='helmsley.commonResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='res_msg', full_name='helmsley.commonResponse.res_msg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=123,
)


_SCOREINFO = _descriptor.Descriptor(
  name='scoreInfo',
  full_name='helmsley.scoreInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rgroup_id', full_name='helmsley.scoreInfo.rgroup_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rank_id', full_name='helmsley.scoreInfo.rank_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rank_score', full_name='helmsley.scoreInfo.rank_score', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='raw_score', full_name='helmsley.scoreInfo.raw_score', index=3,
      number=4, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vol_score', full_name='helmsley.scoreInfo.vol_score', index=4,
      number=5, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=125,
  serialized_end=230,
)


_VOLUMEINFO = _descriptor.Descriptor(
  name='volumeInfo',
  full_name='helmsley.volumeInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='folder_name', full_name='helmsley.volumeInfo.folder_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='folder_path', full_name='helmsley.volumeInfo.folder_path', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dims', full_name='helmsley.volumeInfo.dims', index=2,
      number=3, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='orientation', full_name='helmsley.volumeInfo.orientation', index=3,
      number=4, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='resolution', full_name='helmsley.volumeInfo.resolution', index=4,
      number=5, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='volume_loc_range', full_name='helmsley.volumeInfo.volume_loc_range', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='with_mask', full_name='helmsley.volumeInfo.with_mask', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data_source', full_name='helmsley.volumeInfo.data_source', index=7,
      number=8, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sample_img', full_name='helmsley.volumeInfo.sample_img', index=8,
      number=9, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='scores', full_name='helmsley.volumeInfo.scores', index=9,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _VOLUMEINFO_DATASOURCE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=233,
  serialized_end=547,
)

_VOLUMEINFO.fields_by_name['data_source'].enum_type = _VOLUMEINFO_DATASOURCE
_VOLUMEINFO.fields_by_name['scores'].message_type = _SCOREINFO
_VOLUMEINFO_DATASOURCE.containing_type = _VOLUMEINFO
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['commonResponse'] = _COMMONRESPONSE
DESCRIPTOR.message_types_by_name['scoreInfo'] = _SCOREINFO
DESCRIPTOR.message_types_by_name['volumeInfo'] = _VOLUMEINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), dict(
  DESCRIPTOR = _REQUEST,
  __module__ = 'common_pb2'
  # @@protoc_insertion_point(class_scope:helmsley.Request)
  ))
_sym_db.RegisterMessage(Request)

commonResponse = _reflection.GeneratedProtocolMessageType('commonResponse', (_message.Message,), dict(
  DESCRIPTOR = _COMMONRESPONSE,
  __module__ = 'common_pb2'
  # @@protoc_insertion_point(class_scope:helmsley.commonResponse)
  ))
_sym_db.RegisterMessage(commonResponse)

scoreInfo = _reflection.GeneratedProtocolMessageType('scoreInfo', (_message.Message,), dict(
  DESCRIPTOR = _SCOREINFO,
  __module__ = 'common_pb2'
  # @@protoc_insertion_point(class_scope:helmsley.scoreInfo)
  ))
_sym_db.RegisterMessage(scoreInfo)

volumeInfo = _reflection.GeneratedProtocolMessageType('volumeInfo', (_message.Message,), dict(
  DESCRIPTOR = _VOLUMEINFO,
  __module__ = 'common_pb2'
  # @@protoc_insertion_point(class_scope:helmsley.volumeInfo)
  ))
_sym_db.RegisterMessage(volumeInfo)


# @@protoc_insertion_point(module_scope)
