# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inspectorSync.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='inspectorSync.proto',
  package='helmsley',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x13inspectorSync.proto\x12\x08helmsley\x1a\x0c\x63ommon.proto\"\xa8\x01\n\x05VPMsg\x12\x11\n\tclient_id\x18\x01 \x01(\x05\x12#\n\x08req_type\x18\x02 \x01(\x0e\x32\x11.helmsley.ReqType\x12\x30\n\x10volume_pose_type\x18\x03 \x01(\x0e\x32\x16.helmsley.VPMsg.VPType\x12\x0e\n\x06values\x18\x04 \x03(\x02\"%\n\x06VPType\x12\x07\n\x03POS\x10\x00\x12\t\n\x05SCALE\x10\x01\x12\x07\n\x03ROT\x10\x02\"\x89\x01\n\tGestureOp\x12(\n\x04type\x18\x01 \x01(\x0e\x32\x1a.helmsley.GestureOp.OPType\x12\t\n\x01x\x18\x02 \x01(\x02\x12\t\n\x01y\x18\x03 \x01(\x02\"<\n\x06OPType\x12\x0e\n\nTOUCH_DOWN\x10\x00\x12\x0e\n\nTOUCH_MOVE\x10\x01\x12\t\n\x05SCALE\x10\x02\x12\x07\n\x03PAN\x10\x03\"<\n\x11OperationResponse\x12\'\n\ngesture_op\x18\x01 \x01(\x0b\x32\x13.helmsley.GestureOp*\x1b\n\x07ReqType\x12\x07\n\x03SET\x10\x00\x12\x07\n\x03GET\x10\x01\x32\xde\x01\n\rinspectorSync\x12+\n\x0estartBroadcast\x12\x08.Request\x1a\x0f.commonResponse\x12\x30\n\x0cgsVolumePose\x12\x0f.helmsley.VPMsg\x1a\x0f.commonResponse\x12\x34\n\x0csetGestureOp\x12\x13.helmsley.GestureOp\x1a\x0f.commonResponse\x12\x38\n\rgetOperations\x12\x08.Request\x1a\x1b.helmsley.OperationResponse0\x01\x62\x06proto3')
  ,
  dependencies=[common__pb2.DESCRIPTOR,])

_REQTYPE = _descriptor.EnumDescriptor(
  name='ReqType',
  full_name='helmsley.ReqType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SET', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GET', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=420,
  serialized_end=447,
)
_sym_db.RegisterEnumDescriptor(_REQTYPE)

ReqType = enum_type_wrapper.EnumTypeWrapper(_REQTYPE)
SET = 0
GET = 1


_VPMSG_VPTYPE = _descriptor.EnumDescriptor(
  name='VPType',
  full_name='helmsley.VPMsg.VPType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='POS', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SCALE', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ROT', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=179,
  serialized_end=216,
)
_sym_db.RegisterEnumDescriptor(_VPMSG_VPTYPE)

_GESTUREOP_OPTYPE = _descriptor.EnumDescriptor(
  name='OPType',
  full_name='helmsley.GestureOp.OPType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TOUCH_DOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TOUCH_MOVE', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SCALE', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PAN', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=296,
  serialized_end=356,
)
_sym_db.RegisterEnumDescriptor(_GESTUREOP_OPTYPE)


_VPMSG = _descriptor.Descriptor(
  name='VPMsg',
  full_name='helmsley.VPMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='client_id', full_name='helmsley.VPMsg.client_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='req_type', full_name='helmsley.VPMsg.req_type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='volume_pose_type', full_name='helmsley.VPMsg.volume_pose_type', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='values', full_name='helmsley.VPMsg.values', index=3,
      number=4, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _VPMSG_VPTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=216,
)


_GESTUREOP = _descriptor.Descriptor(
  name='GestureOp',
  full_name='helmsley.GestureOp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='helmsley.GestureOp.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='x', full_name='helmsley.GestureOp.x', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='helmsley.GestureOp.y', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _GESTUREOP_OPTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=219,
  serialized_end=356,
)


_OPERATIONRESPONSE = _descriptor.Descriptor(
  name='OperationResponse',
  full_name='helmsley.OperationResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='gesture_op', full_name='helmsley.OperationResponse.gesture_op', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=358,
  serialized_end=418,
)

_VPMSG.fields_by_name['req_type'].enum_type = _REQTYPE
_VPMSG.fields_by_name['volume_pose_type'].enum_type = _VPMSG_VPTYPE
_VPMSG_VPTYPE.containing_type = _VPMSG
_GESTUREOP.fields_by_name['type'].enum_type = _GESTUREOP_OPTYPE
_GESTUREOP_OPTYPE.containing_type = _GESTUREOP
_OPERATIONRESPONSE.fields_by_name['gesture_op'].message_type = _GESTUREOP
DESCRIPTOR.message_types_by_name['VPMsg'] = _VPMSG
DESCRIPTOR.message_types_by_name['GestureOp'] = _GESTUREOP
DESCRIPTOR.message_types_by_name['OperationResponse'] = _OPERATIONRESPONSE
DESCRIPTOR.enum_types_by_name['ReqType'] = _REQTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

VPMsg = _reflection.GeneratedProtocolMessageType('VPMsg', (_message.Message,), dict(
  DESCRIPTOR = _VPMSG,
  __module__ = 'inspectorSync_pb2'
  # @@protoc_insertion_point(class_scope:helmsley.VPMsg)
  ))
_sym_db.RegisterMessage(VPMsg)

GestureOp = _reflection.GeneratedProtocolMessageType('GestureOp', (_message.Message,), dict(
  DESCRIPTOR = _GESTUREOP,
  __module__ = 'inspectorSync_pb2'
  # @@protoc_insertion_point(class_scope:helmsley.GestureOp)
  ))
_sym_db.RegisterMessage(GestureOp)

OperationResponse = _reflection.GeneratedProtocolMessageType('OperationResponse', (_message.Message,), dict(
  DESCRIPTOR = _OPERATIONRESPONSE,
  __module__ = 'inspectorSync_pb2'
  # @@protoc_insertion_point(class_scope:helmsley.OperationResponse)
  ))
_sym_db.RegisterMessage(OperationResponse)



_INSPECTORSYNC = _descriptor.ServiceDescriptor(
  name='inspectorSync',
  full_name='helmsley.inspectorSync',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=450,
  serialized_end=672,
  methods=[
  _descriptor.MethodDescriptor(
    name='startBroadcast',
    full_name='helmsley.inspectorSync.startBroadcast',
    index=0,
    containing_service=None,
    input_type=common__pb2._REQUEST,
    output_type=common__pb2._COMMONRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='gsVolumePose',
    full_name='helmsley.inspectorSync.gsVolumePose',
    index=1,
    containing_service=None,
    input_type=_VPMSG,
    output_type=common__pb2._COMMONRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='setGestureOp',
    full_name='helmsley.inspectorSync.setGestureOp',
    index=2,
    containing_service=None,
    input_type=_GESTUREOP,
    output_type=common__pb2._COMMONRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='getOperations',
    full_name='helmsley.inspectorSync.getOperations',
    index=3,
    containing_service=None,
    input_type=common__pb2._REQUEST,
    output_type=_OPERATIONRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_INSPECTORSYNC)

DESCRIPTOR.services_by_name['inspectorSync'] = _INSPECTORSYNC

# @@protoc_insertion_point(module_scope)
