# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from proto import common_pb2 as proto_dot_common__pb2
from proto import inspectorSync_pb2 as proto_dot_inspectorSync__pb2


class inspectorSyncStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.gsVolumePose = channel.unary_unary(
        '/helmsley.inspectorSync/gsVolumePose',
        request_serializer=proto_dot_inspectorSync__pb2.VPMsg.SerializeToString,
        response_deserializer=proto_dot_common__pb2.Response.FromString,
        )


class inspectorSyncServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def gsVolumePose(self, request, context):
    """setter
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_inspectorSyncServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'gsVolumePose': grpc.unary_unary_rpc_method_handler(
          servicer.gsVolumePose,
          request_deserializer=proto_dot_inspectorSync__pb2.VPMsg.FromString,
          response_serializer=proto_dot_common__pb2.Response.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'helmsley.inspectorSync', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
