name: demo_1
comments: demo for uist
volume:
  pos: [0.0, 0.0, 0.0]
  scale: [1.0, 1.0, 1.0]
  rotation: [0.81964636, -0.17850566, 0.54435, 0.0, 0.0368403, 0.9646719, 0.26086798,
    0.0, -0.5716845, -0.19376525, 0.7972663, 0.0, 0.0, 0.0, 0.0, 1.0]
camera:
  pos: [0.0, 0.0, 3.0]
  up: [0.0, 1.0, 0.0]
  center: [0.0, 0.0, 2.0]
render mode: Raycasting
transfer function:
  contrast: [1.0, 0.0, 0.22745098, 0.50980395]
  opacity:
  - [1.0, 0.0, 1.12, 0.0, 0.6]
  color scheme: Bright Color
cutting plane:
  status: true
  freeze volume: false
  freeze plane: false
  percentage: 0.2
  ppoint: [0.0, 0.0, 0.31101176]
  pnorm: [0.0, 0.0, -1.0]
mask:
  status: false
  value: [true, true, true, true, true]
